/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dta;

import static dta.Spage.fareRate;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;


public class Mainpage extends javax.swing.JFrame {

    /**
     * Creates new form Mainpage
     */
    public Mainpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        proceed = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        locbox = new javax.swing.JComboBox();
        desbox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Algerian", 1, 36), new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 0, 36), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(960, 600));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("BankGothic Lt BT", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("          From :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 210, 220, 37);

        jLabel3.setFont(new java.awt.Font("BankGothic Lt BT", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("         To  :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(203, 293, 187, 37);

        proceed.setBackground(new java.awt.Color(248, 234, 234));
        proceed.setFont(new java.awt.Font("BankGothic Lt BT", 1, 26)); // NOI18N
        proceed.setForeground(new java.awt.Color(6, 6, 6));
        proceed.setText("Proceed");
        proceed.setBorder(null);
        proceed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });
        jPanel1.add(proceed);
        proceed.setBounds(203, 425, 197, 36);

        exit.setBackground(new java.awt.Color(251, 233, 233));
        exit.setFont(new java.awt.Font("BankGothic Lt BT", 1, 26)); // NOI18N
        exit.setForeground(new java.awt.Color(3, 3, 3));
        exit.setText("Back");
        exit.setBorder(null);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(560, 425, 194, 36);

        locbox.setBackground(new java.awt.Color(102, 102, 255));
        locbox.setFont(new java.awt.Font("BankGothic Lt BT", 1, 26)); // NOI18N
        locbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Location", "Azimpur", "Badda", "Banani", "Dhanmondi", "Elephant Road", "Farmgate", "Gulisthan", "Gulshan", "Jatrabari", "Komlapur", "Malibagh", "Mirpur", "Mohakhali", "Motijheel", "Uttara" }));
        locbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locboxActionPerformed(evt);
            }
        });
        jPanel1.add(locbox);
        locbox.setBounds(418, 211, 326, 37);

        desbox.setBackground(new java.awt.Color(102, 255, 102));
        desbox.setFont(new java.awt.Font("BankGothic Lt BT", 1, 26)); // NOI18N
        desbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Location", "Azimpur", "Badda", "Banani", "Dhanmondi", "Elephant Road", "Farmgate", "Gulisthan", "Gulshan", "Jatrabari", "Komlapur", "Malibagh", "Mirpur", "Mohakhali", "Motijheel", "Uttara" }));
        desbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desboxActionPerformed(evt);
            }
        });
        jPanel1.add(desbox);
        desbox.setBounds(418, 293, 330, 37);

        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 1, 48)); // NOI18N
        jLabel1.setText("      Dhaka Travel Assistant");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, 30, 607, 72);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dta/FreeVector-Travel-Background.jpg"))); // NOI18N
        jPanel1.add(back);
        back.setBounds(0, 0, 1069, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static String loc;
    static String des;
    public static String s3;
    static String check;
    static String check1;
    static String check2;
    String s1;
    String s2;
    
    
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        Front mp=new Front();
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
        // TODO add your handling code here:
        loc=(String) locbox.getSelectedItem();
        des=(String) desbox.getSelectedItem();
             try{     
         
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
 
            Connection con = DriverManager.getConnection("jdbc:odbc:datafile");
     
             Statement st=con.createStatement();
             String name=(String) locbox.getSelectedItem();
             st.executeQuery("SELECT * FROM code where name='"+name+"' ");
             ResultSet rset = st.getResultSet();
             
            while(rset.next())
            {
             
                s1=rset.getString("id");
                //System.out.println(s1);
                //t1.setText(s1);
            }

}
     catch(Exception e){           
           System.out.println(e); 
           
                    
    }
             try{     
         
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
 
            Connection con = DriverManager.getConnection("jdbc:odbc:datafile");
     
             Statement st=con.createStatement();
             String name=(String) desbox.getSelectedItem();
             st.executeQuery("SELECT * FROM code where name='"+name+"' ");
             ResultSet rset = st.getResultSet();
             
            while(rset.next())
            {
                s2=rset.getString("id"); 
                //t2.setText(s2);
            }

}
     catch(Exception e){           
           System.out.println(e); 
           
                    
    }
        
        
        s3=s1+s2;
        
        Spage ob1= new Spage();
        ob1.setVisible(true);
        this.setVisible(false);
             //initializing............
        
             //initializing ends............
        
    }//GEN-LAST:event_proceedActionPerformed

    private void locboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locboxActionPerformed

    private void desboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainpage().setVisible(true);
                
                
            }
        });
        
   
        
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JComboBox desbox;
    private javax.swing.JButton exit;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox locbox;
    private javax.swing.JButton proceed;
    // End of variables declaration//GEN-END:variables
}
